FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git bash tzdata wget

COPY go.mod go.sum ./
RUN go mod download

# air (hot reload)
RUN go install github.com/air-verse/air@latest
COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]